import express from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 4000;

// Enable CORS and JSON parsing
app.use(cors({ origin: true, credentials: true }));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Upload directory setup
const uploadDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir, { recursive: true });
}

// Samples directory for file download tests
const samplesDir = path.join(__dirname, 'samples');
if (!fs.existsSync(samplesDir)) {
  fs.mkdirSync(samplesDir, { recursive: true });
}

// Generate sample files if they do not exist
fs.writeFileSync(path.join(samplesDir, 'test-file.txt'), 'Hello! This is a test file for automation download testing.\nGenerated by AutoTest Playground.');
fs.writeFileSync(path.join(samplesDir, 'sample-data.csv'), 'id,name,role,status\n1,Alice Johnson,QA Lead,Active\n2,Bob Smith,Automation Engineer,Active\n3,Charlie Brown,Developer,Inactive');

const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, uploadDir),
  filename: (req, file, cb) => {
    const cleanName = file.originalname.replace(/[^a-zA-Z0-9._-]/g, '_');
    cb(null, `${Date.now()}-${cleanName}`);
  }
});
const upload = multer({ storage });

// In-memory data store for CRUD tests
let users = [
  { id: 1, name: 'Sarah Connor', email: 'sarah@skynet.net', role: 'Security Lead', status: 'Active', department: 'Engineering' },
  { id: 2, name: 'John Doe', email: 'john.doe@example.com', role: 'QA Engineer', status: 'Active', department: 'Quality Assurance' },
  { id: 3, name: 'Jane Roe', email: 'jane.roe@test.org', role: 'Product Manager', status: 'Pending', department: 'Product' },
  { id: 4, name: 'Bruce Wayne', email: 'bruce@waynecorp.com', role: 'System Architect', status: 'Inactive', department: 'Infrastructure' },
  { id: 5, name: 'Peter Parker', email: 'peter@dailybugle.com', role: 'Junior Tester', status: 'Active', department: 'Quality Assurance' },
];

// Root endpoint
app.get('/', (req, res) => {
  res.send(`
    <html>
      <head><title>AutoTest Playground Server</title></head>
      <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0b0f19; color: #f1f5f9; padding: 48px; text-align: center;">
        <h1 style="color: #38bdf8; font-size: 2rem; margin-bottom: 8px;">AutoTest Backend Server is Running!</h1>
        <p style="color: #94a3b8; font-size: 1.1rem; margin-top: 0;">This is the mock REST API backend on port 4000.</p>
        <div style="margin-top: 32px; padding: 24px; background: #1e293b; border-radius: 12px; display: inline-block;">
          <p style="margin: 0 0 12px 0; color: #cbd5e1;">To access the AutoTest Playground Web App UI:</p>
          <a href="http://localhost:5173" style="color: #38bdf8; font-size: 1.4rem; font-weight: 600; text-decoration: underline;">👉 Open http://localhost:5173</a>
        </div>
      </body>
    </html>
  `);
});

// Health Check
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString(), service: 'AutoTest Playground Backend' });
});

// Dynamic Delay Endpoint for Explicit/Implicit wait tests
app.get('/api/delay/:seconds', async (req, res) => {
  const seconds = Math.min(Math.max(parseInt(req.params.seconds, 10) || 1, 1), 30);
  await new Promise(resolve => setTimeout(resolve, seconds * 1000));
  res.json({
    message: `Response delayed by ${seconds} second(s).`,
    delayedSeconds: seconds,
    receivedAt: new Date().toISOString()
  });
});

// HTTP Status Code tester (200, 201, 400, 401, 403, 404, 500, 502, 503, etc.)
app.all('/api/status/:code', (req, res) => {
  const code = parseInt(req.params.code, 10) || 200;
  const statusMessages = {
    200: 'OK - Request succeeded',
    201: 'Created - Resource successfully created',
    204: 'No Content',
    400: 'Bad Request - Client query or body is invalid',
    401: 'Unauthorized - Authentication token missing or invalid',
    403: 'Forbidden - Access denied to this resource',
    404: 'Not Found - The requested endpoint does not exist',
    422: 'Unprocessable Entity - Semantic validation failed',
    500: 'Internal Server Error - Simulated server crash',
    502: 'Bad Gateway - Simulated proxy failure',
    503: 'Service Unavailable - Simulated server overload'
  };

  if (code === 204) {
    return res.status(204).end();
  }

  res.status(code).json({
    statusCode: code,
    message: statusMessages[code] || `Simulated HTTP ${code} response`,
    query: req.query,
    timestamp: new Date().toISOString()
  });
});

// File Upload
app.post('/api/upload', upload.single('file'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ success: false, error: 'No file uploaded' });
  }
  res.json({
    success: true,
    message: 'File uploaded successfully!',
    file: {
      originalName: req.file.originalname,
      size: req.file.size,
      mimetype: req.file.mimetype,
      savedAs: req.file.filename
    }
  });
});

// File Download
app.get('/api/download/:filename', (req, res) => {
  const requestedFile = req.params.filename;
  const filePath = path.join(samplesDir, requestedFile);

  if (fs.existsSync(filePath)) {
    res.download(filePath);
  } else {
    res.status(404).json({ error: 'File not found for download' });
  }
});

// Available sample files list
app.get('/api/download-list', (req, res) => {
  const files = fs.readdirSync(samplesDir).map(name => {
    const stat = fs.statSync(path.join(samplesDir, name));
    return { name, size: stat.size };
  });
  res.json({ files });
});

// Mock Authentication
app.post('/api/auth/login', (req, res) => {
  const { username, password } = req.body;
  if (username === 'admin' && password === 'password123') {
    return res.json({
      success: true,
      token: 'jwt-token-sample-984712048-admin',
      user: { username: 'admin', role: 'Administrator', fullName: 'System Admin' }
    });
  }
  if (username === 'tester' && password === 'testpass') {
    return res.json({
      success: true,
      token: 'jwt-token-sample-123456789-tester',
      user: { username: 'tester', role: 'QA Tester', fullName: 'Automation Tester' }
    });
  }
  return res.status(401).json({
    success: false,
    message: 'Invalid username or password. Valid accounts: admin/password123 or tester/testpass'
  });
});

// Users CRUD for Table Testing
app.get('/api/users', (req, res) => {
  res.json({ data: users });
});

app.post('/api/users', (req, res) => {
  const { name, email, role, status, department } = req.body;
  if (!name || !email) {
    return res.status(400).json({ error: 'Name and email are required' });
  }
  const newUser = {
    id: users.length > 0 ? Math.max(...users.map(u => u.id)) + 1 : 1,
    name,
    email,
    role: role || 'User',
    status: status || 'Active',
    department: department || 'General'
  };
  users.push(newUser);
  res.status(201).json({ success: true, user: newUser });
});

app.put('/api/users/:id', (req, res) => {
  const id = parseInt(req.params.id, 10);
  const index = users.findIndex(u => u.id === id);
  if (index === -1) {
    return res.status(404).json({ error: 'User not found' });
  }
  users[index] = { ...users[index], ...req.body, id };
  res.json({ success: true, user: users[index] });
});

app.delete('/api/users/:id', (req, res) => {
  const id = parseInt(req.params.id, 10);
  const exists = users.some(u => u.id === id);
  if (!exists) {
    return res.status(404).json({ error: 'User not found' });
  }
  users = users.filter(u => u.id !== id);
  res.json({ success: true, message: `User ${id} deleted.` });
});

app.post('/api/users/reset', (req, res) => {
  users = [
    { id: 1, name: 'Sarah Connor', email: 'sarah@skynet.net', role: 'Security Lead', status: 'Active', department: 'Engineering' },
    { id: 2, name: 'John Doe', email: 'john.doe@example.com', role: 'QA Engineer', status: 'Active', department: 'Quality Assurance' },
    { id: 3, name: 'Jane Roe', email: 'jane.roe@test.org', role: 'Product Manager', status: 'Pending', department: 'Product' },
    { id: 4, name: 'Bruce Wayne', email: 'bruce@waynecorp.com', role: 'System Architect', status: 'Inactive', department: 'Infrastructure' },
    { id: 5, name: 'Peter Parker', email: 'peter@dailybugle.com', role: 'Junior Tester', status: 'Active', department: 'Quality Assurance' },
  ];
  res.json({ success: true, message: 'User list reset to default dataset', data: users });
});

// HTML iFrame targets for automation frame switching tests
app.get('/iframe/simple', (req, res) => {
  res.setHeader('Content-Type', 'text/html');
  res.send(`<!DOCTYPE html>
<html>
<head>
  <title>Simple iFrame Content</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 20px; background: #f8fafc; color: #1e293b; }
    .box { background: white; border: 1px solid #cbd5e1; border-radius: 8px; padding: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }
    button { background: #3b82f6; color: white; border: none; padding: 8px 16px; border-radius: 6px; cursor: pointer; font-weight: 500; }
    button:hover { background: #2563eb; }
    .result { margin-top: 12px; font-weight: 600; color: #16a34a; }
  </style>
</head>
<body>
  <div class="box">
    <h3 data-testid="iframe-heading">Inside Simple iFrame</h3>
    <p>This content is hosted inside an iframe (&apos;/iframe/simple&apos;). Test automation tools must switch context to this frame to interact.</p>
    <input type="text" id="iframe-input" data-testid="iframe-input" placeholder="Type inside iframe..." style="padding: 6px 10px; border: 1px solid #94a3b8; border-radius: 4px; margin-right: 8px;" />
    <button id="iframe-btn" data-testid="iframe-button" onclick="document.getElementById('iframe-result').innerText = 'Submitted: ' + document.getElementById('iframe-input').value">Click Me</button>
    <div id="iframe-result" data-testid="iframe-result" class="result"></div>
  </div>
</body>
</html>`);
});

app.get('/iframe/nested', (req, res) => {
  res.setHeader('Content-Type', 'text/html');
  res.send(`<!DOCTYPE html>
<html>
<head>
  <title>Parent Frame</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 16px; background: #f1f5f9; color: #0f172a; }
    iframe { border: 2px dashed #94a3b8; border-radius: 6px; width: 100%; height: 200px; background: white; }
  </style>
</head>
<body>
  <h4 data-testid="parent-frame-text">Outer Frame Level 1</h4>
  <p>Contains a child iframe below:</p>
  <iframe src="/iframe/simple" data-testid="child-iframe" id="child-iframe"></iframe>
</body>
</html>`);
});

app.listen(PORT, () => {
  console.log(`AutoTest Backend Server running on http://localhost:${PORT}`);
});
